version: "3.8"
services:
  api-campaigns-prod:
    image: "$DOCKER_IMAGE"
    environment:
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - BOT_SMTP_MAIL=$BOT_SMTP_MAIL
      - BOT_SMTP_PASSWORD=$BOT_SMTP_PASSWORD
      - BOT_SMTP_PORT=$BOT_SMTP_PORT
      - BOT_SMTP_SECURITY=$BOT_SMTP_SECURITY
      - BOT_SMTP_URL=$BOT_SMTP_URL
      - ASPNETCORE_ENVIRONMENT=Production
      - SENTRY_DSN=$SENTRY_DSN_API_CAMPAIGNS
    networks:
      - samnet
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=samnet

        - traefik.http.routers.prod__api_campaigns.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`${PATH_NAME}`)
        - traefik.http.routers.prod__api_campaigns.entrypoints=https
        - traefik.http.routers.prod__api_campaigns.service=prod__api_campaigns
        - traefik.http.routers.prod__api_campaigns.tls.certresolver=letsencrypt

        - traefik.http.services.prod__api_campaigns.loadbalancer.server.port=8890
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s

networks:
  samnet:
    external: true
